modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "letsplay"
version = "${version}"
displayName = "Let's Play Server Utilities"
authors = "Jonathan Ho"
description = "A small utility mod for the Let's Play server."

[[dependencies.letsplay]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.letsplay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"